language: python

python:
  - "3.5"

install:
  - python setup.py install
  - pip install coveralls[yaml]

script:
  - python3 testrunner.py --with-coverage --cover-package=ripl

after_success:
  - coveralls
